<a href="https://colab.research.google.com/github/Manusree1324/AIML-lab/blob/main/log_values.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
list=["apple","banana"]
print(list)

['apple', 'banana']


In [3]:
array=[1,2,3,4]
print(array)

[1, 2, 3, 4]


In [4]:
import numpy as np
my_list=np.list(["apple","banana",1])
print(my_list[0])

AttributeError: module 'numpy' has no attribute 'list'

In [5]:
import numpy as np
fruits=["cherry","mango"]
print(fruits)

['cherry', 'mango']


In [6]:
import pandas as pd
fruits=["cherry","mango"]
print(fruits)


['cherry', 'mango']


In [13]:
import numpy as np
number=np.array([1,2,3,4,5])
print(type(number))

<class 'numpy.ndarray'>


In [19]:
import numpy as np
arr1=np.array([1,2,3,4,5,6,7])
arr2=np.array([1,2,3,4,5,6,7])
#addition
c=arr1+arr2
print(c)
#subtraction
c=arr1-arr2
print(c)
#division
c=arr1/arr2
print(c)
#multiplication
c=arr1*arr2
print(c)


[ 2  4  6  8 10 12 14]
[0 0 0 0 0 0 0]
[1. 1. 1. 1. 1. 1. 1.]
[ 1  4  9 16 25 36 49]


In [24]:
import numpy as np
arr1=np.array([1,5,7,3])
arr2=np.array([4,3,2,5])
result=np.add(arr1,arr2)
output_text=f"addition of two arrays:{result}"
print(output_text)

addition of two arrays:[5 8 9 8]


In [27]:
import numpy as np
my_list=[1,2,3,4,5]
my_array=np.array(my_list)
sin_x = np.sin(my_array)
print(f"sin({my_array}) = {sin_x}")
log_x = np.log(x)
print(f"log({my_array}) = {log_x}")
log2_x = np.log2(my_array)
print(f"log2({my_array}) = {log2_x}")
exp_x = np.exp(my_array)
print(f"exp({my_array}) = {exp_x}")

sin([1 2 3 4 5]) = [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
log([1 2 3 4 5]) = 0.6931471805599453
log2([1 2 3 4 5]) = [0.         1.         1.5849625  2.         2.32192809]
exp([1 2 3 4 5]) = [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
